# Uncomment this line to define a global platform for your project
platform :ios, "8.0"
target "SpeechTherapyGame" do
pod 'FrameAccessor', '~> 1.3.2'
pod 'MagicalRecord'
pod 'PNChart'
pod 'ActionSheetPicker-3.0'
pod 'MZFormSheetController'#, :git => 'https://github.com/m1entus/MZFormSheetController.git'
pod 'Masonry'
pod 'FMDB'
pod 'ChameleonFramework'
pod 'TheAmazingAudioEngine'
pod 'SpinKit', '~> 1.1'
pod 'EZAudio'
pod 'Fabric'
pod 'Crashlytics'

end


