# Uncomment this line to define a global platform for your project
platform :ios, "7.0"
target "SpeechTherapyGame" do
pod 'FrameAccessor', '~> 1.3.2'
pod 'MagicalRecord'
pod 'GraphKit'
pod 'ActionSheetPicker-3.0'
end


