# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'MFCCDemo' do

pod 'TheAmazingAudioEngine'
pod 'FMDB'
pod 'MZFormSheetController'
pod 'EZAudio'

end

target 'MFCCDemoTests' do

end

