# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "Spectrum" do
    
    pod 'DspFilters'
    pod 'EZAudio'
    pod 'SWRevealViewController'
    pod 'FrameAccessor'
    #pod 'CrashlyticsFramework'
    pod 'SpinKit', '~> 1.2.0'
end

target "SpectrumTests" do

end

